name: Build .NET Solution with VSBuild Reusable Template 71a9a2d3-a98a-4caa-96ab-affca411ecda

on:
  push:
    branches: [ main ]

jobs:
  call-vsbuild-template:
    uses: ./.github/workflows/template_VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda.yml
    with:
      runsOn: windows-latest
      solution: "AspnetCoreMvcFull.sln"         # Optional, or leave blank to auto-detect
      vsVersion: "17.0"
      platform: "Any CPU"
      configuration: "Release"
      msbuildArgs: "/p:WarningLevel=4"
      restoreNugetPackages: true
      clean: true
      maximumCpuCount: true
      msbuildArchitecture: "x64"           # Architecture: 'x86' or 'x64'
      createLogFile: true
      logFileVerbosity: "normal"
      logProjectEvents: true
