name: VSBuild Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/vsbuildtask-reusable.yml
    with:
      runsOn: "windows-latest" 
      logProjectEvents: true
      vsVersion: "latest"
      enableDefaultLogger: true
      restoreNugetArgs: "-NoHttpCache"
      platform: "Any CPU"
      configuration: "Release"
      maxCpu: 8
      clean: true
      vsbuildArguments: ""
      createLogFile: true
      logFileVerbosity: "detailed"
